
ctrl.btn.GameID.txt           = Game ID ...
ctrl.btn.Hint.txt             = Hint
ctrl.btn.New.txt              = New
ctrl.btn.Preferences.txt      = Settings ...
ctrl.btn.RedoStep.txt         = Redo +
ctrl.btn.UndoStep.txt         = Undo -
ctrl.btn.YourGame.txt         = Your Game
ctrl.lbl.SolutionFinished.txt = !!!
ctrl.lbl.SolverResults.txt    = Computed Solutions

gameId.Info1.txt                   = Copy the Game ID from the text box to save the current game and your solution progress.
gameId.Info2.txt                   = Paste a Game ID into the text box to continue a saved game.
gameId.Title.txt                   = Game ID
gameId.btn.Cancel.txt              = Cancel
gameId.btn.Copy.txt                = Copy
gameId.btn.OK.txt                  = OK
gameId.btn.Paste.txt               = Paste
gameId.msg.ApplyGameId.Error.title = Error
gameId.msg.ApplyGameId.Error.txt   = Could not apply this Game ID
gameId.msg.CopyPaste.Error.title   = Error
gameId.msg.CopyPaste.Error.txt     = An error occurred
gameId.txt.Colors.txt              = Colors:
gameId.txt.Size.txt                = Size:
gameId.txt.Solution.txt            = Solution:
gameId.txt.StartPos.txt            = Starting Position:
gameId.txt.complete.txt            = complete

pref.Title.txt                  = Settings
pref.BoardColorNumbersEnum.ALL.txt  = all
pref.BoardColorNumbersEnum.NEXT.txt = next
pref.BoardColorNumbersEnum.NONE.txt = none
pref.btn.Cancel.txt             = Cancel
pref.btn.Defaults.txt           = Restore Defaults
pref.btn.OK.txt                 = OK
pref.GridLinesEnum.ALL.txt      = all
pref.GridLinesEnum.COLORS.txt   = colors
pref.GridLinesEnum.NONE.txt     = none
pref.HighlightColorEnum.BLACK.txt = black
pref.HighlightColorEnum.WHITE.txt = white
pref.HighlightColorEnum.BLUE.txt  = blue
pref.lbl.BoardColorNumbers.txt  = Color Numbers
pref.lbl.CellSize.txt           = Cell Size (Pixels)
pref.lbl.ColorScheme.txt        = Color Scheme
pref.lbl.LookAndFeel.txt        = Look & Feel
pref.lbl.ControlPanelEast.txt   = Control panel
pref.ControlPanelEast.left.txt  = left
pref.ControlPanelEast.right.txt = right
pref.lbl.GridLines.txt          = Grid Lines
pref.lbl.Height.txt             = Height (Rows)
pref.lbl.HighlightColor.txt     = Marker Color
pref.lbl.HighlightTransparency.txt = Marker Transparency
pref.lbl.NumColors.txt          = Number of Colors
pref.lbl.StartPos.txt           = Starting Position
pref.lbl.Width.txt              = Width (Columns)
pref.StartPositionEnum.BOTTOM_LEFT.txt  = bottom left
pref.StartPositionEnum.BOTTOM_RIGHT.txt = bottom right
pref.StartPositionEnum.CENTRAL.txt      = central
pref.StartPositionEnum.TOP_LEFT.txt     = top left
pref.StartPositionEnum.TOP_RIGHT.txt    = top right
